services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /Users/luyao/mysql-data-2:/var/lib/mysql
    environment:
      MYSQL_DATABASE: aaa
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/luyao/aaa:/data
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
